const API_BASE = location.origin;
const app = document.getElementById('app');

const storage = {
  get session(){ try{return JSON.parse(localStorage.getItem('dmp_prod_session')||'null')}catch{return null} },
  set session(v){ v?localStorage.setItem('dmp_prod_session',JSON.stringify(v)):localStorage.removeItem('dmp_prod_session') },
  get deviceId(){ let v=localStorage.getItem('dmp_prod_device_id'); if(!v){v=`WEB-${crypto.randomUUID()}`;localStorage.setItem('dmp_prod_device_id',v)} return v },
  get activeMatch(){ try{return JSON.parse(localStorage.getItem('dmp_prod_active_match')||'null')}catch{return null} },
  set activeMatch(v){ v?localStorage.setItem('dmp_prod_active_match',JSON.stringify(v)):localStorage.removeItem('dmp_prod_active_match') }
};

const state={session:storage.session,route:'home',teams:[],players:[],matches:[],rankings:[],hall:[],online:false,activeMatch:storage.activeMatch};
const headers=()=>state.session?.accessToken?{'Authorization':`Bearer ${state.session.accessToken}`,'X-Device-Id':storage.deviceId}:{};
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const guid=()=>crypto.randomUUID();
const nowIso=()=>new Date().toISOString();
const unwrap=r=>r?.payload??r;

async function api(path,options={}){
  const response=await fetch(`${API_BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...headers(),...(options.headers||{})}});
  if(response.status===401){storage.session=null;state.session=null;renderAuth('انتهت الجلسة. سجّل الدخول مجددًا.');throw new Error('unauthorized')}
  const payload=response.status===204?null:await response.json().catch(()=>null);
  if(!response.ok)throw new Error(payload?.message||'تعذر تنفيذ العملية.');
  state.online=true;return payload;
}

function rankFromXp(xp=0){if(xp>=5000)return'Majlis Legend';if(xp>=3500)return'Majlis Master';if(xp>=2500)return'Diamond';if(xp>=1700)return'Platinum';if(xp>=1000)return'Gold';if(xp>=500)return'Silver';if(xp>=150)return'Bronze';return'Unranked'}
function levelFromXp(xp=0){return Math.max(1,Math.floor(xp/100)+1)}
function seasonInfo(){const length=30*86400000;const epoch=Date.UTC(2026,0,1);const elapsed=Math.max(0,Date.now()-epoch);const id=Math.floor(elapsed/length)+1;const start=new Date(epoch+(id-1)*length);const end=new Date(start.getTime()+length);return{id,start,end,remaining:Math.max(0,Math.ceil((end-Date.now())/86400000))}}
function badgesForTeam(t){const result=[];if((t.totalMatches||0)>=5&&(t.trustScore??100)>=95)result.push({name:'موثّق',rarity:'Rare'});if((t.totalMatches||0)>=15&&(t.winRate||0)>=50&&(t.trustScore??100)>=95)result.push({name:'ثقة',rarity:'Rare'});if((t.consecutiveWins||0)>=5)result.push({name:'سلسلة انتصارات',rarity:'Epic'});if((t.melesCount||0)>=3)result.push({name:'هيمنة',rarity:'Legendary'});if(t.hallOfFameMember||t.hasHallOfFameBadge)result.push({name:'Hall of Fame',rarity:'Immortal'});return result}
function hallEligible(t){return (t.lifetimeWins||t.wins||0)>=20&&(t.lifetimeXP||t.xp||0)>=1500&&(t.trustScore??100)>=90}

function renderAuth(error=''){
  app.innerHTML=`<section class="boot-screen" style="display:block;min-height:auto;padding-top:6vh"><div class="brand-mark">♛</div><h1>Domino Majlis PRO</h1><p>الحساب السحابي الرسمي</p><div class="card auth-card"><div class="auth-tabs"><button class="primary" id="loginMode">تسجيل الدخول</button><button class="secondary" id="registerMode">إنشاء حساب</button></div><label>اسم المستخدم</label><input class="field" id="username" autocomplete="username"><label class="field-label">كلمة المرور</label><input class="field" id="password" type="password" autocomplete="current-password"><button class="primary" id="submitAuth">متابعة</button><p class="message" id="authMessage">${escapeHtml(error)}</p></div></section>`;
  let mode='login';const login=document.getElementById('loginMode'),register=document.getElementById('registerMode');
  login.onclick=()=>{mode='login';login.className='primary';register.className='secondary'};
  register.onclick=()=>{mode='register';register.className='primary';login.className='secondary'};
  document.getElementById('submitAuth').onclick=async()=>{const username=document.getElementById('username').value.trim(),password=document.getElementById('password').value,msg=document.getElementById('authMessage');if(username.length<3||password.length<8){msg.textContent='اسم المستخدم 3 أحرف على الأقل وكلمة المرور 8 أحرف على الأقل.';return}msg.textContent='جارٍ الاتصال...';try{const s=await api(`/api/preview/${mode}`,{method:'POST',body:JSON.stringify({username,password,deviceId:storage.deviceId})});storage.session=s;state.session=s;await bootAuthenticated()}catch(e){if(e.message!=='unauthorized')msg.textContent=e.message}};
}

async function health(){try{state.online=(await fetch(`${API_BASE}/api/health`)).ok}catch{state.online=false}}
async function loadResource(name){return (await api(`/api/v1/${name}?includeDeleted=false`).catch(()=>[])).map(unwrap).filter(Boolean)}
async function loadPlayers(){state.players=await loadResource('players')}
async function loadMatches(){state.matches=(await loadResource('matches')).sort((a,b)=>new Date(b.lastPlayedTime||b.matchDate)-new Date(a.lastPlayedTime||a.matchDate))}
async function loadRankings(){state.rankings=await loadResource('rankings')}
async function loadHall(){state.hall=await loadResource('profiles')}
async function loadTeams(){const basic=await api('/api/preview/me/teams').catch(()=>[]);const rich=await loadResource('teams');const map=new Map(rich.map(t=>[t.teamId,t]));state.teams=basic.map(t=>({...map.get(t.teamId),teamId:t.teamId,teamName:map.get(t.teamId)?.teamName||t.name,name:t.name}));for(const t of rich)if(!state.teams.some(x=>x.teamId===t.teamId))state.teams.push({...t,name:t.teamName})}
async function bootAuthenticated(){await Promise.allSettled([loadTeams(),loadPlayers(),loadMatches(),loadRankings(),loadHall(),health()]);renderShell()}

const teamName=id=>state.teams.find(t=>t.teamId===id)?.teamName||state.teams.find(t=>t.teamId===id)?.name||id||'فريق';
const playerName=id=>state.players.find(p=>p.playerId===id)?.playerName||'';
const teamOptions=(selected='')=>`<option value="">اختر فريقًا</option>${state.teams.map(t=>`<option value="${escapeHtml(t.teamId)}" ${t.teamId===selected?'selected':''}>${escapeHtml(t.teamName||t.name)}</option>`).join('')}`;
const playerOptions=(selected='')=>`<option value="">بدون لاعب</option>${state.players.map(p=>`<option value="${escapeHtml(p.playerId)}" ${p.playerId===selected?'selected':''}>${escapeHtml(p.playerName)}</option>`).join('')}`;

function topBar(){const u=state.session?.user||{},p=state.players.find(x=>x.playerId===u.playerId)||state.players[0],initial=(p?.playerName||u.displayName||'?')[0].toUpperCase();return `<header class="topbar"><div class="wallet-chip"><span>🪙</span><strong>0</strong><button data-route="store">+</button></div><div class="wallet-chip"><span>💎</span><strong>0</strong><button data-route="store">+</button></div><button class="avatar-button" data-route="profile"><span>${escapeHtml(initial)}</span><span class="level-badge">${p?.playerLevel||1}</span></button><button class="icon-button" data-route="settings">⚙</button></header>`}
function teamCard(t){return `<article class="list-item"><div class="emblem" style="border-color:${escapeHtml(t.colorHex||'#8d6824')}">${escapeHtml(t.emblem||'♜')}</div><div><b>${escapeHtml(t.teamName||t.name)}</b><br><small>${escapeHtml(playerName(t.player1Id)||t.player1||'—')} / ${escapeHtml(playerName(t.player2Id)||t.player2||'—')}</small><br><small>${escapeHtml(t.rank||'Unranked')} · ${t.xp||0} XP · ثقة ${t.trustScore??100}%</small></div><button class="mini-button" data-edit-team="${escapeHtml(t.teamId)}">تعديل</button></article>`}
function playerCard(p){return `<article class="list-item"><div class="emblem">${escapeHtml((p.playerName||'?')[0])}</div><div><b>${escapeHtml(p.playerName)}</b><br><small>${escapeHtml(p.playerRank||'Unranked')} · المستوى ${p.playerLevel||1}</small><br><small>${p.wins||0} فوز · ${p.losses||0} خسارة · ثقة ${p.trustScore??100}%</small></div><button class="mini-button" data-edit-player="${escapeHtml(p.playerId)}">تعديل</button></article>`}

function statisticsView(){const finished=state.matches.filter(m=>m.isFinished),meles=finished.filter(m=>m.hasMeles).length,rounds=finished.reduce((n,m)=>n+(m.roundsHistory?.length||0),0),top=state.teams.slice().sort((a,b)=>(b.xp||0)-(a.xp||0))[0];return `<h1 class="page-title">الإحصائيات</h1><p class="page-subtitle">ملخص الأداء الكامل للحساب.</p><section class="metrics"><div class="metric"><b>${finished.length}</b><span>مباراة مكتملة</span></div><div class="metric"><b>${rounds}</b><span>الجولات</span></div><div class="metric"><b>${meles}</b><span>الملص</span></div></section><section class="card"><h2>أفضل فريق</h2>${top?teamCard(top):'<p class="muted">لا توجد بيانات كافية.</p>'}</section>`}
function seasonView(){const s=seasonInfo();const standings=state.teams.slice().sort((a,b)=>(b.seasonXP||b.xp||0)-(a.seasonXP||a.xp||0));return `<h1 class="page-title">الموسم ${s.id}</h1><p class="page-subtitle">متبقي ${s.remaining} يومًا على نهاية الموسم.</p><section class="card season-card"><div><small>بداية الموسم</small><b>${s.start.toLocaleDateString('ar-IQ')}</b></div><div><small>نهاية الموسم</small><b>${s.end.toLocaleDateString('ar-IQ')}</b></div></section><section class="card"><h2>ترتيب الموسم</h2>${standings.length?standings.map((t,i)=>`<article class="ranking-row"><strong>#${i+1}</strong><div><b>${escapeHtml(t.teamName||t.name)}</b><small>${escapeHtml(t.rank||rankFromXp(t.xp||0))}</small></div><span>${t.seasonXP||t.xp||0} XP</span></article>`).join(''):'<p class="muted">لا توجد فرق بعد.</p>'}</section>`}
function badgesView(){return `<h1 class="page-title">الشارات</h1><p class="page-subtitle">الشارات المكتسبة وفق الأداء والثقة.</p>${state.teams.map(t=>`<section class="card"><h2>${escapeHtml(t.teamName||t.name)}</h2><div class="badge-grid">${badgesForTeam(t).length?badgesForTeam(t).map(b=>`<div class="badge-card"><b>${escapeHtml(b.name)}</b><small>${escapeHtml(b.rarity)}</small></div>`).join(''):'<p class="muted">لم تُكتسب شارات بعد.</p>'}</div></section>`).join('')||'<section class="card"><p class="muted">لا توجد فرق.</p></section>'}`}
function hallView(){const candidates=state.teams.filter(t=>t.hallOfFameMember||t.hasHallOfFameBadge||hallEligible(t));return `<h1 class="page-title">Hall of Fame</h1><p class="page-subtitle">السجل الدائم لأبرز الفرق.</p><section class="card hall-hero"><div class="brand-mark small">♛</div><h2>قاعة المجد</h2><p>تُحفظ إنجازات الفرق المؤهلة بصورة دائمة.</p></section><section class="card">${candidates.length?candidates.map((t,i)=>`<article class="hall-row"><strong>${i+1}</strong><div><b>${escapeHtml(t.teamName||t.name)}</b><small>${t.lifetimeWins||t.wins||0} فوز · ${t.lifetimeXP||t.xp||0} XP · ثقة ${t.trustScore??100}%</small></div><span>♛</span></article>`).join(''):'<p class="muted">لم يتأهل أي فريق بعد.</p>'}</section>`}
function rankingsView(){const rows=state.teams.slice().sort((a,b)=>(b.xp||0)-(a.xp||0));return `<h1 class="page-title">التصنيفات</h1><p class="page-subtitle">ترتيب الفرق حسب XP.</p><section class="card">${rows.length?rows.map((t,i)=>`<article class="ranking-row"><strong>#${i+1}</strong><div><b>${escapeHtml(t.teamName||t.name)}</b><small>${escapeHtml(t.rank||rankFromXp(t.xp||0))}</small></div><span>${t.xp||0} XP</span></article>`).join(''):'<p class="muted">لا توجد فرق بعد.</p>'}</section>`}

const routes={
  home:()=>`<h1 class="page-title">الرئيسية</h1><p class="page-subtitle">مجلسك، فرقك، ولاعبوك ومبارياتك.</p><section class="card hero"><h2>مرحبًا ${escapeHtml(state.session?.user?.displayName||'')}</h2><div class="metrics"><div class="metric"><b>${state.teams.length}</b><span>الفرق</span></div><div class="metric"><b>${state.players.length}</b><span>اللاعبون</span></div><div class="metric"><b>${state.matches.length}</b><span>المباريات</span></div></div></section><div class="section-grid"><button class="action-card" data-route="players"><h3>اللاعبون</h3><p>الملفات والإحصائيات.</p></button><button class="action-card" data-route="teams"><h3>الفرق</h3><p>التشكيلات والهوية.</p></button><button class="action-card" data-route="matches"><h3>مباراة</h3><p>الجولات والنتائج.</p></button><button class="action-card" data-route="season"><h3>الموسم</h3><p>الترتيب الموسمي.</p></button><button class="action-card" data-route="hall"><h3>Hall of Fame</h3><p>الإنجازات الدائمة.</p></button><button class="action-card" data-route="statistics"><h3>الإحصائيات</h3><p>تحليل الأداء.</p></button></div>`,
  players:()=>`<h1 class="page-title">اللاعبون</h1><p class="page-subtitle">ملفات اللاعبين المرتبطة بالحساب.</p><section class="card"><input id="playerId" type="hidden"><label>اسم اللاعب</label><input id="playerName" class="field" maxlength="40"><label class="field-label">النبذة</label><input id="playerBio" class="field" maxlength="160"><button id="savePlayer" class="primary">حفظ اللاعب</button><p id="playerMessage" class="message"></p></section><section class="card">${state.players.length?state.players.map(playerCard).join(''):'<p class="muted">لا يوجد لاعبون بعد.</p>'}</section>`,
  teams:()=>`<h1 class="page-title">الفرق</h1><p class="page-subtitle">إنشاء الفرق وتحديد تشكيلاتها.</p><section class="card"><input id="teamId" type="hidden"><label>اسم الفريق</label><input id="teamName" class="field"><div class="round-grid"><div><label class="field-label">اللاعب الأول</label><select id="player1" class="field">${playerOptions()}</select></div><div><label class="field-label">اللاعب الثاني</label><select id="player2" class="field">${playerOptions()}</select></div></div><button id="saveTeam" class="primary">حفظ الفريق</button><p id="teamMessage" class="message"></p></section><section class="card">${state.teams.length?state.teams.map(teamCard).join(''):'<p class="muted">لا توجد فرق بعد.</p>'}</section>`,
  matches:()=>state.activeMatch?matchBoard():matchSetup(),history:()=>historyView(),rankings:()=>rankingsView(),season:()=>seasonView(),statistics:()=>statisticsView(),badges:()=>badgesView(),hall:()=>hallView(),
  profile:()=>{const u=state.session?.user||{},p=state.players.find(x=>x.playerId===u.playerId)||state.players[0];return `<h1 class="page-title">الملف الشخصي</h1><section class="card profile-hero"><div class="avatar-button">${escapeHtml((p?.playerName||u.displayName||'?')[0])}</div><div><h2>${escapeHtml(p?.playerName||u.displayName||'')}</h2><p>${escapeHtml(p?.playerRank||'Unranked')} · المستوى ${p?.playerLevel||1}</p></div></section><section class="metrics"><div class="metric"><b>${p?.playerXP||0}</b><span>XP</span></div><div class="metric"><b>${p?.trustScore??100}%</b><span>الثقة</span></div><div class="metric"><b>${p?.wins||0}</b><span>الانتصارات</span></div></section><button class="secondary" data-route="badges">عرض الشارات</button>`},
  settings:()=>`<h1 class="page-title">الإعدادات</h1><section class="card"><div class="list-item"><div class="emblem">☁</div><div><b>حالة السحابة</b><br><small>${state.online?'متصل':'غير متصل'}</small></div><span>${state.online?'✓':'!'}</span></div><button id="logout" class="secondary">تسجيل الخروج</button></section>`,
  store:()=>`<h1 class="page-title">المتجر</h1><section class="card"><p class="muted">يتم ربط المتجر والمخزون في الدفعة التالية.</p></section>`
};

function matchSetup(){return `<h1 class="page-title">مباراة جديدة</h1><section class="card"><label>الفريق الأول</label><select id="team1" class="field">${teamOptions()}</select><label class="field-label">الفريق الثاني</label><select id="team2" class="field">${teamOptions()}</select><label class="field-label">القواعد</label><select id="rules" class="field"><option value="local">محلي</option><option value="international">دولي</option></select><label class="check-row"><input type="checkbox" id="ranked"> مباراة مصنفة</label><button id="startMatch" class="primary" ${state.teams.length<2?'disabled':''}>بدء المباراة</button><p id="matchMessage" class="message">${state.teams.length<2?'يجب إنشاء فريقين على الأقل.':''}</p></section>`}
function matchBoard(){const m=state.activeMatch;return `<h1 class="page-title">المباراة الجارية</h1><p class="page-subtitle">الجولة ${m.roundNumber} — ${m.isLocalRules?'محلي':'دولي'}</p><section class="card score-board"><div class="score-team"><span>${escapeHtml(m.team1Name)}</span><b>${m.team1Score}</b></div><div class="versus">VS</div><div class="score-team"><span>${escapeHtml(m.team2Name)}</span><b>${m.team2Score}</b></div></section><section class="card"><div class="round-grid"><div><label>${escapeHtml(m.team1Name)}</label><input id="round1" class="field" type="number" min="0" value="0"></div><div><label>${escapeHtml(m.team2Name)}</label><input id="round2" class="field" type="number" min="0" value="0"></div></div><button id="addRound" class="primary">حفظ الجولة</button><p id="roundMessage" class="message"></p></section><section class="card"><h2>سجل الجولات</h2>${roundHistory(m)}</section><div class="section-grid"><button id="saveExit" class="secondary">حفظ والخروج</button><button id="cancelMatch" class="secondary">إلغاء المباراة</button></div>`}
function roundHistory(m){return m.roundsHistory?.length?m.roundsHistory.map((r,i)=>`<div class="list-item"><div class="emblem">${i+1}</div><div><b>${r.team1RoundScore} - ${r.team2RoundScore}</b></div><span>${new Date(r.playedAt).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})}</span></div>`).join(''):'<p class="muted">لم تسجل جولات بعد.</p>'}
function historyView(){return `<h1 class="page-title">سجل المباريات</h1><section class="card">${state.matches.length?state.matches.map(m=>`<article class="match-history"><div><b>${escapeHtml(m.team1Name)} <span>${m.team1Score}</span></b><small>ضد</small><b>${escapeHtml(m.team2Name)} <span>${m.team2Score}</span></b></div><div class="history-meta"><strong>${m.isFinished?'منتهية':'غير مكتملة'}</strong><small>${new Date(m.matchDate||m.lastPlayedTime).toLocaleDateString('ar-IQ')}</small></div></article>`).join(''):'<p class="muted">لا توجد مباريات.</p>'}</section>`}
function evaluateWinner(m){if(m.team1Score===m.team2Score)return null;const max=Math.max(m.team1Score,m.team2Score),min=Math.min(m.team1Score,m.team2Score),winnerId=m.team1Score>m.team2Score?m.team1Id:m.team2Id,winnerName=m.team1Score>m.team2Score?m.team1Name:m.team2Name;if(m.isLocalRules&&max>=101&&min<25)return{winnerId,winnerName,hasMeles:true};if(max>=151)return{winnerId,winnerName,hasMeles:false};return null}
async function putResource(resource,id,payload){await api(`/api/v1/${resource}/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({payload})})}
async function persistMatch(m){await putResource('matches',m.matchId,m)}
async function persistTeam(t){await putResource('teams',t.teamId,t)}
async function persistPlayer(p){await putResource('players',p.playerId,p)}

async function updateStatsAfterMatch(m){if(!m.isFinished||m.statsApplied)return;const winnerId=m.winnerTeamId,loserId=winnerId===m.team1Id?m.team2Id:m.team1Id;for(const team of state.teams.filter(t=>[winnerId,loserId].includes(t.teamId))){const win=team.teamId===winnerId;team.totalMatches=(team.totalMatches||0)+1;team.gamesPlayed=(team.gamesPlayed||0)+1;team.wins=(team.wins||0)+(win?1:0);team.losses=(team.losses||0)+(win?0:1);team.lifetimeWins=(team.lifetimeWins||0)+(win?1:0);team.lifetimeLosses=(team.lifetimeLosses||0)+(win?0:1);team.melesCount=(team.melesCount||0)+(win&&m.hasMeles?1:0);team.lifetimeMeles=(team.lifetimeMeles||0)+(win&&m.hasMeles?1:0);team.consecutiveWins=win?(team.consecutiveWins||0)+1:0;team.consecutiveLosses=win?0:(team.consecutiveLosses||0)+1;const gain=win?(m.hasMeles?75:50):10;team.xp=(team.xp||0)+gain;team.seasonXP=(team.seasonXP||0)+gain;team.lifetimeXP=(team.lifetimeXP||0)+gain;team.rank=rankFromXp(team.xp);team.winRate=Math.round((team.wins/team.totalMatches)*100);team.lastMatchDate=nowIso();team.currentSeasonId=seasonInfo().id;if(hallEligible(team)){team.hallOfFameMember=true;team.hasHallOfFameBadge=true;team.hallOfFameDate=team.hallOfFameDate||nowIso()}await persistTeam(team);for(const pid of [team.player1Id,team.player2Id].filter(Boolean)){const p=state.players.find(x=>x.playerId===pid);if(!p)continue;p.totalMatches=(p.totalMatches||0)+1;p.wins=(p.wins||0)+(win?1:0);p.losses=(p.losses||0)+(win?0:1);p.currentWinStreak=win?(p.currentWinStreak||0)+1:0;p.bestWinStreak=Math.max(p.bestWinStreak||0,p.currentWinStreak||0);p.playerXP=(p.playerXP||0)+gain;p.seasonXP=(p.seasonXP||0)+gain;p.lifetimeXP=(p.lifetimeXP||0)+gain;p.playerRank=rankFromXp(p.playerXP);p.playerLevel=levelFromXp(p.playerXP);p.winRate=Math.round((p.wins/p.totalMatches)*100);p.lastActiveAt=nowIso();await persistPlayer(p)}}m.statsApplied=true;await persistMatch(m);await Promise.allSettled([loadTeams(),loadPlayers(),loadRankings()])}

async function completeRound(){const m=state.activeMatch,msg=document.getElementById('roundMessage'),s1=Math.max(0,Number(document.getElementById('round1').value||0)),s2=Math.max(0,Number(document.getElementById('round2').value||0));if(s1===0&&s2===0){msg.textContent='أدخل نقاط الجولة.';return}m.team1Score+=s1;m.team2Score+=s2;m.roundsHistory.push({roundNumber:m.roundNumber,team1RoundScore:s1,team2RoundScore:s2,playedAt:nowIso()});m.roundNumber+=1;m.lastPlayedTime=nowIso();const w=evaluateWinner(m);if(w){m.isFinished=true;m.isLocked=true;m.matchEndDate=nowIso();m.winnerTeamId=w.winnerId;m.winnerTeamName=w.winnerName;m.winnerTeam=w.winnerName;m.hasMeles=w.hasMeles}storage.activeMatch=m;await persistMatch(m);if(w){await updateStatsAfterMatch(m);storage.activeMatch=null;state.activeMatch=null;await loadMatches();state.route='history'}renderShell()}

function nav(){return `<nav class="bottom-nav"><div class="bottom-nav-inner"><button class="nav-button ${state.route==='home'?'active':''}" data-route="home"><span>⌂</span>الرئيسية</button><button class="nav-button ${state.route==='players'?'active':''}" data-route="players"><span>●</span>اللاعبون</button><button class="nav-button ${state.route==='teams'?'active':''}" data-route="teams"><span>♜</span>الفرق</button><button class="nav-button ${state.route==='matches'?'active':''}" data-route="matches"><span>◆</span>مباراة</button><button class="nav-button ${state.route==='rankings'?'active':''}" data-route="rankings"><span>★</span>التصنيف</button><button class="nav-button ${state.route==='hall'?'active':''}" data-route="hall"><span>♛</span>المجد</button></div></nav>`}
function renderShell(){app.innerHTML=`${topBar()}<main>${(routes[state.route]||routes.home)()}</main>${nav()}`;bindNavigation();bindRouteActions()}
function bindNavigation(){document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>{state.route=el.dataset.route;renderShell()})}
function fillPlayerForm(id){const p=state.players.find(x=>x.playerId===id);if(!p)return;document.getElementById('playerId').value=p.playerId;document.getElementById('playerName').value=p.playerName||'';document.getElementById('playerBio').value=p.bio||''}
function fillTeamForm(id){const t=state.teams.find(x=>x.teamId===id);if(!t)return;document.getElementById('teamId').value=t.teamId;document.getElementById('teamName').value=t.teamName||t.name||'';document.getElementById('player1').value=t.player1Id||'';document.getElementById('player2').value=t.player2Id||''}

function bindRouteActions(){
  if(state.route==='players'){
    document.getElementById('savePlayer').onclick=async()=>{const id=document.getElementById('playerId').value||`PLY-${guid().replaceAll('-','').toUpperCase()}`,name=document.getElementById('playerName').value.trim(),bio=document.getElementById('playerBio').value.trim(),msg=document.getElementById('playerMessage');if(!name){msg.textContent='اسم اللاعب مطلوب.';return}const old=state.players.find(p=>p.playerId===id)||{};const p={...old,playerId:id,playerName:name,bio,playerRank:old.playerRank||'Unranked',playerXP:old.playerXP||0,playerLevel:old.playerLevel||1,seasonXP:old.seasonXP||0,lifetimeXP:old.lifetimeXP||0,trustScore:old.trustScore??100,totalMatches:old.totalMatches||0,wins:old.wins||0,losses:old.losses||0,createdAt:old.createdAt||nowIso(),lastUpdatedAt:nowIso()};await persistPlayer(p);await loadPlayers();renderShell()};
    document.querySelectorAll('[data-edit-player]').forEach(b=>b.onclick=()=>fillPlayerForm(b.dataset.editPlayer));
  }
  if(state.route==='teams'){
    document.getElementById('saveTeam').onclick=async()=>{const id=document.getElementById('teamId').value||`TEAM-${guid().replaceAll('-','').toUpperCase()}`,name=document.getElementById('teamName').value.trim(),p1=document.getElementById('player1').value,p2=document.getElementById('player2').value,msg=document.getElementById('teamMessage');if(!name){msg.textContent='اسم الفريق مطلوب.';return}if(p1&&p2&&p1===p2){msg.textContent='اختر لاعبين مختلفين.';return}if(!state.teams.some(t=>t.teamId===id))await api('/api/preview/me/teams',{method:'POST',body:JSON.stringify({name})}).catch(()=>null);const old=state.teams.find(t=>t.teamId===id)||{};const t={...old,teamId:id,teamName:name,name,player1Id:p1,player2Id:p2,player1:playerName(p1),player2:playerName(p2),xp:old.xp||0,seasonXP:old.seasonXP||0,lifetimeXP:old.lifetimeXP||0,wins:old.wins||0,losses:old.losses||0,totalMatches:old.totalMatches||0,melesCount:old.melesCount||0,rank:old.rank||'Unranked',trustScore:old.trustScore??100,colorHex:old.colorHex||'#FFD700',emblem:old.emblem||'♜',currentSeasonId:seasonInfo().id};await persistTeam(t);await loadTeams();renderShell()};
    document.querySelectorAll('[data-edit-team]').forEach(b=>b.onclick=()=>fillTeamForm(b.dataset.editTeam));
  }
  if(state.route==='matches'&&!state.activeMatch){const btn=document.getElementById('startMatch');if(btn)btn.onclick=()=>{const t1=document.getElementById('team1').value,t2=document.getElementById('team2').value,msg=document.getElementById('matchMessage');if(!t1||!t2||t1===t2){msg.textContent='اختر فريقين مختلفين.';return}const a=state.teams.find(t=>t.teamId===t1)||{},b=state.teams.find(t=>t.teamId===t2)||{};const m={matchId:guid(),team1Id:t1,team2Id:t2,team1Name:teamName(t1),team2Name:teamName(t2),team1Players:[playerName(a.player1Id),playerName(a.player2Id)].filter(Boolean).join('، '),team2Players:[playerName(b.player1Id),playerName(b.player2Id)].filter(Boolean).join('، '),team1Player1Id:a.player1Id||'',team1Player2Id:a.player2Id||'',team2Player1Id:b.player1Id||'',team2Player2Id:b.player2Id||'',team1Score:0,team2Score:0,roundNumber:1,isLocalRules:document.getElementById('rules').value==='local',matchDate:nowIso(),matchEndDate:null,matchDurationMinutes:0,roundsHistory:[],winnerTeam:'',winnerTeamName:'',winnerTeamId:'',hasMeles:false,isDraw:false,isFinished:false,isLocked:false,lastPlayedTime:nowIso(),displayTitle:`${teamName(t1)} ضد ${teamName(t2)}`,rankedMatch:document.getElementById('ranked').checked,isVerified:false,team1Emblem:a.emblem||'',team2Emblem:b.emblem||'',team1ColorHex:a.colorHex||'#FFD700',team2ColorHex:b.colorHex||'#FFD700'};state.activeMatch=m;storage.activeMatch=m;renderShell()}};
  if(state.route==='matches'&&state.activeMatch){document.getElementById('addRound').onclick=()=>completeRound().catch(e=>document.getElementById('roundMessage').textContent=e.message);document.getElementById('saveExit').onclick=async()=>{await persistMatch(state.activeMatch);await loadMatches();state.route='home';renderShell()};document.getElementById('cancelMatch').onclick=()=>{if(confirm('هل تريد إلغاء المباراة؟')){storage.activeMatch=null;state.activeMatch=null;renderShell()}}}
  if(state.route==='settings')document.getElementById('logout').onclick=async()=>{try{await api('/api/preview/logout',{method:'POST'})}catch{}storage.session=null;state.session=null;renderAuth()};
}

state.session?bootAuthenticated():renderAuth();