const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();
const id=p=>`${p}-${crypto.randomUUID().replaceAll('-','').toUpperCase()}`;
async function hash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256));}
async function body(r){try{return await r.json()}catch{return {}}}
async function currentUser(request,env){const h=request.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return null;const token=h.slice(7).trim();const row=await env.DB.prepare(`SELECT u.application_user_id,u.player_id,u.username FROM sessions s JOIN users u ON u.application_user_id=s.application_user_id WHERE s.token=? AND s.expires_at>?`).bind(token,new Date().toISOString()).first();return row?{token,user:{applicationUserId:row.application_user_id,playerId:row.player_id,displayName:row.username}}:null;}
export default {async fetch(request,env){const u=new URL(request.url),p=u.pathname;
if(p==='/api/health')return json({service:'DominoMajlisPRO.Cloudflare',status:'healthy',persistence:'d1',utc:new Date().toISOString()});
if(p==='/api/preview/register'&&request.method==='POST'){const b=await body(request),username=(b.username||'').trim(),password=b.password||'';if(username.length<3||password.length<8)return json({message:'اسم المستخدم 3 أحرف على الأقل وكلمة المرور 8 أحرف على الأقل.'},400);if(await env.DB.prepare('SELECT 1 FROM users WHERE username=? COLLATE NOCASE').bind(username).first())return json({message:'اسم المستخدم مستخدم بالفعل.'},409);const salt=crypto.getRandomValues(new Uint8Array(16)),app=id('USR'),player=id('PLY'),token=hex(crypto.getRandomValues(new Uint8Array(32))),expires=new Date(Date.now()+12*3600e3).toISOString();await env.DB.batch([env.DB.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').bind(app,player,username,hex(salt),await hash(password,salt),new Date().toISOString()),env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(token,app,expires)]);return json({accessToken:token,expiresAt:expires,user:{applicationUserId:app,playerId:player,displayName:username}});}
if(p==='/api/preview/login'&&request.method==='POST'){const b=await body(request),row=await env.DB.prepare('SELECT * FROM users WHERE username=? COLLATE NOCASE').bind((b.username||'').trim()).first();if(!row)return json({message:'بيانات الدخول غير صحيحة.'},401);const salt=Uint8Array.from(row.password_salt.match(/.{2}/g).map(x=>parseInt(x,16)));if(await hash(b.password||'',salt)!==row.password_hash)return json({message:'بيانات الدخول غير صحيحة.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32))),expires=new Date(Date.now()+12*3600e3).toISOString();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(token,row.application_user_id,expires).run();return json({accessToken:token,expiresAt:expires,user:{applicationUserId:row.application_user_id,playerId:row.player_id,displayName:row.username}});}
if(p==='/api/preview/logout'&&request.method==='POST'){const h=request.headers.get('authorization')||'';if(h.startsWith('Bearer '))await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(h.slice(7).trim()).run();return new Response(null,{status:204});}
if(p==='/api/preview/me/teams'){const s=await currentUser(request,env);if(!s)return json({message:'انتهت الجلسة.'},401);if(request.method==='GET'){const r=await env.DB.prepare('SELECT team_id AS teamId,name,created_at AS createdAt FROM teams WHERE application_user_id=? ORDER BY created_at DESC').bind(s.user.applicationUserId).all();return json(r.results||[]);}if(request.method==='POST'){const b=await body(request),name=(b.name||'').trim();if(!name)return json({message:'اسم الفريق مطلوب.'},400);const teamId=id('TEAM'),createdAt=new Date().toISOString();await env.DB.prepare('INSERT INTO teams VALUES(?,?,?,?)').bind(teamId,s.user.applicationUserId,name,createdAt).run();return json({teamId,name,createdAt},201);}}
return env.ASSETS.fetch(request);}};
